### ISSUE TITLE
Pricing for OEM

### ISSUE THREAD

**Issue by olliluotonen** [EvoxComputing/c1fapp-issues#4]
Hi Guys,

I'm working on a project where we would like to build our own CI Sensor and i would like to use your feeds to populate the data with, but since the traffic might be quite heavy, i think that the OEM license would be required - could you provide pricing for it? 

Much appreciated,

Olli

**Comment by evoxco** [comment]
Hi Olli
This is for opening issues related to the platform. Please see the FAQ for more information about heavy usage of the service.
https://www.c1fapp.com/cifapp/faq/

Thanks!
